INSERT INTO CARTA (ID_CARTA) VALUES (1);

INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2023-01-12', 3, 'https://i.imgur.com/u3m9HqL.png', 'Foto de burguer', 15.50,15.50, 1, 'Una explosión de sabores únicos: carne de rubia gallega dry aged, queso cheddar madurado, bacon bits, pepinillos caseros, crema de galleta, cebolla crujiente y nuestra exclusiva salsa BFP. Ideal para los paladares atrevidos.', 'Provocacion', 'HAMBURGUESA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2024-01-12', 4, 'https://i.imgur.com/olYoEVG.png', 'Foto de hamburguesa clásica', 18.00,18.00, 1, 'Una versión gourmet de la clásica cheeseburger: carne de rubia gallega dry aged, crema de queso payoyo, bacon bits crujientes y nuestra inconfundible salsa BFP. Tradición con un toque de distinción.', 'Payoya', 'HAMBURGUESA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-11-12', 5, 'https://i.imgur.com/9BpQi2z.png', 'Foto de hamburguesa gourmet con foie', 20.50,20.50, 1, 'Exquisita combinación de sabores premium: carne de rubia gallega dry aged con cheddar madurado, coronada con un lingote de foie y nuestra inigualable salsa de cecina de León. Una experiencia de lujo.', 'Donald', 'HAMBURGUESA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2021-12-12', 4, 'https://i.imgur.com/WURtvZ9.jpeg', 'Foto de hamburguesa con costilla y triple cheddar', 12.00,12.00, 1, 'Carne de rubia gallega acompañada con 110g de costilla de cerdo cocinada a baja temperatura durante 24 horas, triple cheddar madurado, y una combinación explosiva de salsas foodporn y BBQ. Una joya callejera.', 'Street burguer', 'HAMBURGUESA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2022-07-20', 3, 'https://i.imgur.com/G3fOw8p.jpeg', 'Foto de hamburguesa campeona de Andalucía', 17.00,17.00, 1, 'Inspirada en la cocina tradicional: rubia gallega dry aged, cheddar madurado, panceta ibérica y una salsa de carne cocinada lentamente durante 72 horas. Galardonada como la mejor hamburguesa de Andalucía.', 'Abuela', 'HAMBURGUESA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2023-05-16', 4, 'https://i.imgur.com/zUbsHpw.jpeg', 'Foto de hamburguesa con chistorra y huevo frito', 14.50,14.50, 1, 'Nuestra campeona de sabor: carne de rubia gallega con bacon ahumado crunch, doble cheddar y una sorprendente emulsión de huevo frito con chistorra. Ganadora por derecho propio.', 'Winner23', 'HAMBURGUESA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-02-15', 5, 'https://i.imgur.com/SkL6dgT.jpeg', 'Foto de burguer', 9.00,9.00, 1, 'Doble patty de buey gallego, acompañado de cecina premium y nuestra salsa BFP especial. Una hamburguesa intensa, jugosa y absolutamente irresistible.', 'Tifa', 'HAMBURGUESA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2024-01-18', 4, 'https://i.imgur.com/qw6KoZl.jpeg', 'Foto de hamburguesa vegana con base de garbanzos', 16.50,16.50, 1, 'Nuestra opción 100% vegetal: deliciosa base de garbanzos especiada, con ingredientes frescos y una textura sorprendentemente sabrosa. Ideal para quienes buscan sabor sin carne.', 'Vegana', 'HAMBURGUESA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 8, 'https://i.imgur.com/5Iy9IFo.jpeg', 'Foto de bebida', 2.50,2.50, 1, 'La bebida más icónica del mundo, con su sabor inconfundible y burbujeante. Perfecta para acompañar cualquier plato.', 'Coca-cola', 'BEBIDA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 7, 'https://i.imgur.com/HpmOUu3.jpeg', 'Foto de nestle', 2.50,2.50, 1, 'Refrescante té frío con un toque exótico de maracuyá. Dulce, ácido y absolutamente delicioso.', 'Te', 'BEBIDA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 3, 'https://i.imgur.com/2j7XedE.png', 'Foto de agua', 1.50,1.50, 1, 'Agua mineral natural, ideal para refrescarte y acompañar una comida sin añadidos. Pura y ligera.', 'Agua', 'BEBIDA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 10, 'https://i.imgur.com/1VmC7uM.jpeg', 'Foto de cerveza', 3.50,3.50, 1, 'Cerveza artesanal rubia, fresca y con carácter. El acompañante ideal para cualquier hamburguesa de la carta.', 'Cerveza', 'BEBIDA');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 10, 'https://i.imgur.com/u8nDHkx.jpeg', 'Foto de tarta de queso', 6.50,6.50, 1, 'Tarta de queso payoyo horneada lentamente para lograr una textura cremosa y un sabor intenso. Una delicia para los amantes del queso.', 'Tarta de queso', 'POSTRE');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 6, 'https://i.imgur.com/oxEarjm.jpeg', 'Foto de tarta de chocolate', 4.50,4.50, 1, 'Irresistible tarta de tres chocolates: negro, con leche y blanco. Un postre cremoso, suave y adictivo para los más golosos.', 'Tarta de chocolate', 'POSTRE');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 8, 'https://i.imgur.com/jPXD9jp.jpeg', 'Foto de torrija', 7.00,7.00, 1, 'Nuestra torrija gourmet, caramelizada al punto perfecto, servida con una bola de helado de vainilla. Tradición y dulzura en cada bocado.', 'Torrija con helado', 'POSTRE');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 7, 'https://i.imgur.com/lmELhrQ.jpeg', 'Foto de patatas', 4.50,4.50, 1, 'Crujientes patatas bañadas en queso fundido y generosamente cubiertas con jugoso pulled pork. El entrante perfecto para compartir (o no).', 'Patatas con pulled pork', 'ENTRANTE');
INSERT INTO PRODUCTO (FECHA, POPULARIDAD, URL, TXT_ALTERNATIVO, PRECIO,PRECIO_ORIGINAL, ID_CARTA, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 6, 'https://i.imgur.com/xBpUkBW.jpeg', 'Foto de croquetas', 5.50,5.50, 1, 'Deliciosas croquetas artesanas rellenas de chuletón de buey gallego, con rebozado crujiente y un interior cremoso e intenso. Un clásico reinventado.', 'Croquetas', 'ENTRANTE');

