INSERT INTO CARTA (ID_CARTA) VALUES (1);

INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA , ID , DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 3,'https://postimg.cc/nj8RB2LP', 15.50, 1, 1 , 'buen sabor', 'abuela', 'HAMBURGUESA');


-- Hamburguesa clásica
INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA, ID, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 4,'https://postimg.cc/bGSVZWqn', 18.00, 1, 2, 'con queso cheddar', 'Clásica', 'HAMBURGUESA');

-- Bebida refrescante
INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA, ID, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 5,'https://postimg.cc/dk8WBCkt', 5.50, 1, 3, 'limón natural', 'Limonada Fresca', 'BEBIDA');

-- Postre tradicional
INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA, ID, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 4,'https://postimg.cc/FkNTnK3b', 12.00, 1, 4, 'con helado de vainilla', 'Tarta de Manzana', 'POSTRE');

-- Hamburguesa picante
INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA, ID, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 3,'https://postimg.cc/9zB2XR8h', 17.00, 1, 5, 'salsa de jalapeños', 'Picante', 'HAMBURGUESA');

-- Café especial
INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA, ID, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 4,'https://postimg.cc/Mf59k8mC', 4.50, 1, 6, 'tostado colombiano', 'Café Premium', 'BEBIDA');

-- Helado artesanal
INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA, ID, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 5,'https://postimg.cc/rzTcLC9j', 9.00, 1, 7, 'con toppings', 'Helado Cookie', 'POSTRE');

-- Hamburguesa vegana
INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA, ID, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 4,'https://postimg.cc/rKFkDV3t', 16.50, 1, 8, 'base de garbanzos', 'Vegana', 'HAMBURGUESA');

-- Batido cremoso
INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA, ID, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 5,'https://postimg.cc/w7fdLKY4', 7.00, 1, 9, 'con leche de almendras', 'Batido de Fresa', 'BEBIDA');

-- Brownie caliente
INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA, ID, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 5,'https://postimg.cc/Z93kGCBX', 10.00, 1, 10, 'con nueces', 'Brownie Chocolate', 'POSTRE');

-- Hamburguesa BBQ
INSERT INTO PRODUCTO (FECHA, POPULARIDAD,URL, PRECIO, CARTA_ID_CARTA, ID, DESCRIPCION, NOMBRE, TIPO_PRODUCTO) VALUES ('2025-01-12', 5,'https://postimg.cc/0zBH2P1x', 20.00, 1, 11, 'salsa barbacoa', 'BBQ Special', 'HAMBURGUESA');